### ISSUE TITLE
Roadmap v2

### ISSUE THREAD

**Issue by privatenumber** [Nutlope/aicommits#164]
- [x] Migrate to chatGPT instead of GPT-3
- [x] Add alias `aic`
- [x] Add opt-in languages flag where it returns the commit in different languages
- [x] Proxy support https://github.com/Nutlope/aicommits/pull/139
- [x] Add exclude paths flag https://github.com/Nutlope/aicommits/pull/162
- [x] Add config to choose GPT-4 (given the user has access to it)
- [x] Support `--all` flag from `git commit` https://github.com/Nutlope/aicommits/issues/171
- [ ] Non-interactive mode (auto-commit) https://github.com/Nutlope/aicommits/pull/75
- [x] Add support for conventional commits as a flag that users can enable
- [ ] Add support for diffs greater than 200 lines by grabbing the diff per file, optional flag
- [ ] Add ability to specify a commit message from inside aicommit if user doesn't like generated one https://github.com/Nutlope/aicommits/issues/110
- [ ] Add opt-in emoji flag to preface commits with an emoji, use [this](https://gitmoji.dev) as a guide https://github.com/Nutlope/aicommits/pull/163
- [ ] Build landing page for the 2.0 launch

**Comment by NorkzYT** [comment]
This comment is to list out the current GitHub Pull Requests that correlate to the `Roadmap`.
The following list will be updated.

Non-interactive mode (auto-commit)
https://github.com/Nutlope/aicommits/pull/75

Proxy support
https://github.com/Nutlope/aicommits/pull/139
 
Add exclude paths flag
https://github.com/Nutlope/aicommits/pull/162

Add support for conventional commits as a flag that users can enable
Add opt-in emoji flag to preface commits with an emoji, use [this](https://gitmoji.dev/) as a guide
https://github.com/Nutlope/aicommits/pull/163

Add support for diffs greater than 200 lines by grabbing the diff per file, optional flag
https://github.com/Nutlope/aicommits/issues/81?

Add ability to specify a commit message from inside aicommit if user doesn't like generated one
Feature request:
https://github.com/Nutlope/aicommits/issues/110

Build landing page for the 2.0 launch
?

**Comment by privatenumber** [comment]
Thanks, I updated the roadmap

**Comment by NorkzYT** [comment]
> Thanks, I updated the roadmap

No problem mate.

**Comment by phields** [comment]
feature request: custom OPENAI API Host
ref:
https://github.com/chathub-dev/chathub/blob/3255ec23abeb8535291e92c58e4ed7d25573566c/src/services/user-config.ts

**Comment by WiegerWolf** [comment]
> Add support for conventional commits as a flag that users can enable
this is [now complete](https://github.com/Nutlope/aicommits/releases/tag/v1.11.0)

**Comment by Chenpeel** [comment]
#286 #302

**Comment by insign** [comment]
Sad to say but looks abandoned.
